name = "Dubins"
uuid = "c4b27c1d-289f-5655-aa69-f096df7d9e2b"
authors = ["Kaarthik Sundar <kaarthik01sundar@gmail.com>", "Devansh Agrawal <devansh@umich.edu>"]
repo = "https://github.com/kaarthiksundar/Dubins.jl.git"
version = "1.2.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Logging = "1.11.0"
LoggingExtras = "~0.4, ~0.5, ~1"
StaticArrays = "1.9.12"
julia = "^1"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
